name: Playwright Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install chromium dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        libwoff2dec.so.1.0.2 \
        libvpx.so.7 \
        libevent-2.1.so.7 \
        libopus.so.0 \
        libgstallocators-1.0.so.0 \
        libgstapp-1.0.so.0 \
        libgstpbutils-1.0.so.0 \
        libgstaudio-1.0.so.0 \
        libgsttag-1.0.so.0 \
        libgstvideo-1.0.so.0 \
        libgstgl-1.0.so.0 \
        libgstcodecparsers-1.0.so.0 \
        libgstfft-1.0.so.0 \
        libharfbuzz-icu.so.0 \
        libhyphen.so.0 \
        libmanette-0.2.so.0 \
        libflite.so.1 \
        libflite_usenglish.so.1 \
        libflite_cmu_grapheme_lang.so.1 \
        libflite_cmu_grapheme_lex.so.1 \
        libflite_cmu_indic_lang.so.1 \
        libflite_cmu_indic_lex.so.1 \
        libflite_cmulex.so.1 \
        libflite_cmu_time_awb.so.1 \
        libflite_cmu_us_awb.so.1 \
        libflite_cmu_us_kal16.so.1 \
        libflite_cmu_us_kal.so.1 \
        libflite_cmu_us_rms.so.1 \
        libflite_cmu_us_slt.so.1 \
        libGLESv2.so.2 \
        libx264.so

    - name: Install node dependencies
      run: npm i
    
    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run Playwright tests
      run: npx playwright test
      env:
        DESIRED_TEST_URL: ${{ secrets.DESIRED_TEST_URL }}
        DESIRED_TEST_ARTICLES: ${{ secrets.DESIRED_TEST_ARTICLES }}