name: Playwright Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
        DESIRED_TEST_URL: https://news.ycombinator.com/newest
        DESIRED_TEST_ARTICLES: 100
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

      # Install dependencies and browsers with Playwright Action
    - name: Install Playwright dependencies
      uses: microsoft/playwright-github-action@v1
      with:
        install-deps: true  # This installs the required system dependencies for Playwright

    - name: Install node dependencies
      run: npm i
    
    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run Playwright tests
      run: npx playwright test
      